SELECT
    F.ID, N.FISH_NAME, F.LENGTH
FROM
    FISH_INFO F
JOIN
    FISH_NAME_INFO N
ON
    F.FISH_TYPE = N.FISH_TYPE
WHERE
    F.LENGTH = (
        SELECT
            MAX(F2.LENGTH)
        FROM FISH_INFO F2
        WHERE F2.FISH_TYPE = F.FISH_TYPE
)
ORDER BY
    F.ID;